server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quassar
    userName: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: janobprizident@gmail.com
      password: ecgyiraunmdyakcg
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true

security:
  jwt:
    secret-key: "MWIxNzc4NDg0MjMzNDVmZGY4ZjgwZTBkMDU4ZWVjYWNiMTdkZjMwNTJhOTNmNDZiYWVmN2MyOGQyNjQ2MzdiMTc="
    expiration-time: 3600000
    refresh-expiration-time: 86400000

